### ISSUE TITLE
Prototypical access to Curriculum-Object on right half of website

### ISSUE THREAD

**Issue by thomasbaar** [thomasbaar/dslModullandkarte#6]
Dig into details of transfering the Model-object (or Curriculum-object) to the View-page on the right half; allow to access all properties of this object.

As a result, just printed out the name of the Curriculum on the canvas.

Document the main structures of the implementation.

**Comment by ThomasPompe** [comment]
I isolated the langium Framework and embedded it into a vue / quasar application. Parsed and transferred the complete AST inside langium and transferred it to the frondend framework. Then parsed it again to create a clear data structure, which can be used for creating our tile design.
New run command for both frameworks is: **npm run start-all** 
Which starts the Langium Framework as our DSL interpreter and the Frontend to visualize.
Next steps should be visualizing our tiles and integrating the connections for predeccessors etc.
